spring:
  application:
    name: rate-limiter-example
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000

ratelimit:
  limit: 60
  windowMs: 1000
  excludePatterns:
    - /actuator/health


