spring:
  application:
    name: rate-limiter-example
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000

ratelimit:
  account:
    limit: 60
    windowMs: 1000
    enabled: true
  product:
    limit: 60
    windowMs: 1000
    enabled: true
  excludePatterns:
    - /actuator/health
  allow-on-error: false


