spring:
  application:
    name: rate-limiter-example
#  profiles:
#    active: dev
  data:
    redis:
      client-type: lettuce
      timeout: 3s
      cluster:
        nodes:
          - localhost:7001
          - localhost:7002
          - localhost:7003

rate-limiter:
  account:
    allow-on-error: false
    limit: 60
    windowMs: 1000
    enabled: true
  product:
    allow-on-error: false
    limit: 60
    windowMs: 1000
    enabled: true
  excludePatterns:
    - /actuator/health
    - /actuator

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      access: unrestricted
  metrics:
    tags:
      application: ${spring.application.name:app}

logging:
  style: CONSOLE
  level:
    br:
      com:
        rodrigogurgel: DEBUG