spring:
  application:
    name: rate-limiter-example
  profiles:
    active: dev
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000

rate-limiter:
  account:
    limit: 60
    windowMs: 1000
    enabled: true
  product:
    limit: 60
    windowMs: 1000
    enabled: true
  excludePatterns:
    - /actuator/health
    - /actuator
  allow-on-error: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      access: unrestricted
  metrics:
    tags:
      application: ${spring.application.name:app}

logging:
  style: STASH