{
 "title": "Rate Limit Dashboard",
 "tags": [
  "rate-limit",
  "k6",
  "redis"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "RPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RPS — Total",
   "type": "timeseries",
   "description": "Throughpu",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum (rate(http_server_requests_seconds_count[$__rate_interval]))",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "RPS — Total (Allowed)",
   "type": "timeseries",
   "description": "Throughput efetivo (somente allowed=true).",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum (rate(http_server_requests_seconds_count{status=\"200\"}[$__rate_interval]))",
     "legendFormat": "RPS (allowed)"
    }
   ]
  },
  {
   "title": "RPS — Total (Disallowed)",
   "type": "timeseries",
   "description": "Throughput efetivo (somente allowed=true).",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum (rate(http_server_requests_seconds_count{status=\"429\"}[$__rate_interval]))",
     "legendFormat": "RPS (disallowed)"
    }
   ]
  },
  { "title": "Account", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Account — Total",
   "type": "timeseries",
   "description": "RPS por Account (allowed + disallowed).",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (account) ( rate(app_rate_limit_account_requests_total[$__rate_interval]) )",
     "legendFormat": "{{account}}"
    }
   ]
  },
  {
   "title": "Account — Allowed x Disallowed",
   "type": "timeseries",
   "description": "Comparativo Allowed x Disallowed por Account.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (account, allowed) ( rate(app_rate_limit_account_requests_total[$__rate_interval]) )",
     "legendFormat": "{{account}} | allowed={{allowed}}"
    }
   ]
  },
  {
   "title": "Account — Allowed",
   "type": "timeseries",
   "description": "RPS Allowed por Account.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (account) ( rate(app_rate_limit_account_requests_total{allowed=\"true\"}[$__rate_interval]) )",
     "legendFormat": "{{account}}"
    }
   ]
  },
  {
   "title": "Account — Disallowed (429/s)",
   "type": "timeseries",
   "description": "RPS Disallowed (429/s) por Account.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (account) ( rate(app_rate_limit_account_requests_total{allowed=\"false\"}[$__rate_interval]) )",
     "legendFormat": "{{account}}"
    }
   ]
  },
  { "title": "Product", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Product — Total",
   "type": "timeseries",
   "description": "RPS por Product (allowed + disallowed).",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (product) ( rate(app_rate_limit_product_requests_total[$__rate_interval]) )",
     "legendFormat": "{{product}}"
    }
   ]
  },
  {
   "title": "Product — Allowed x Disallowed",
   "type": "timeseries",
   "description": "Comparativo Allowed x Disallowed por Product.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (product, allowed) ( rate(app_rate_limit_product_requests_total[$__rate_interval]) )",
     "legendFormat": "{{product}} | allowed={{allowed}}"
    }
   ]
  },
  {
   "title": "Product — Allowed (limite 60)",
   "type": "timeseries",
   "description": "RPS Allowed por Product.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (product) ( rate(app_rate_limit_product_requests_total{allowed=\"true\"}[$__rate_interval]) )",
     "legendFormat": "{{product}}"
    }
   ]
  },
  {
   "title": "Product — Disallowed (429/s)",
   "type": "timeseries",
   "description": "RPS Disallowed (429/s) por Product.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (product) ( rate(app_rate_limit_product_requests_total{allowed=\"false\"}[$__rate_interval]) )",
     "legendFormat": "{{product}}"
    }
   ]
  }
 ]
}