services:
  redis-node-1:
    image: redis:8.2-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis-conf/redis-node-1.conf:/usr/local/etc/redis/redis.conf
      - redis-data-1:/data
    ports:
      - "7001:7001"
      - "7101:7101"
    expose:
      - "7001"
      - "7101"
    network_mode: "host"

  redis-node-2:
    image: redis:8.2-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis-conf/redis-node-2.conf:/usr/local/etc/redis/redis.conf
      - redis-data-2:/data
    ports:
      - "7002:7002"
      - "7102:7102"
    expose:
      - "7002"
      - "7102"
    network_mode: "host"

  redis-node-3:
    image: redis:8.2-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis-conf/redis-node-3.conf:/usr/local/etc/redis/redis.conf
      - redis-data-3:/data
    ports:
      - "7003:7003"
      - "7103:7103"
    expose:
      - "7003"
      - "7103"
    network_mode: "host"

  redis-node-4:
    image: redis:8.2-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis-conf/redis-node-4.conf:/usr/local/etc/redis/redis.conf
      - redis-data-4:/data
    ports:
      - "7004:7004"
      - "7104:7104"
    expose:
      - "6379"
      - "7004"
      - "7104"
    network_mode: "host"

  redis-node-5:
    image: redis:8.2-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis-conf/redis-node-5.conf:/usr/local/etc/redis/redis.conf
      - redis-data-5:/data
    ports:
      - "7005:7005"
      - "7105:7105"
    expose:
      - "6379"
      - "7005"
      - "7105"
    network_mode: "host"

  redis-node-6:
    image: redis:8.2-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis-conf/redis-node-6.conf:/usr/local/etc/redis/redis.conf
      - redis-data-6:/data
    ports:
      - "7006:7006"
      - "7106:7106"
    expose:
      - "6379"
      - "7006"
      - "7106"
    network_mode: "host"

  redis-cluster-creator:
    image: redis:8.2-alpine
    network_mode: "host"
    command: >
      redis-cli --cluster create 
      host.docker.internal:7001 host.docker.internal:7002 host.docker.internal:7003 
      host.docker.internal:7004 host.docker.internal:7005 host.docker.internal:7006
      --cluster-replicas 1 --cluster-yes
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
      - redis-node-6

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    environment:
      - RI_ACCEPT_TERMS_AND_CONDITIONS=yes
    network_mode: "host"
    ports:
      - "8001:8001"
      - "5540:5540"
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
      - redis-node-6
    volumes:
      - redisinsight-data:/data

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus  # caminho do volume de dados
    ports:
      - "127.0.0.1:9090:9090"            # só local
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus      # persistir TSDB/WAL
    networks:
      monitoring:
        aliases: [prometheus]

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=changeme123!
      - GF_USERS_DEFAULT_THEME=dark
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    ports:
      - "127.0.0.1:3000:3000"            # só local
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
    depends_on:
      - prometheus
    networks:
      monitoring:
        aliases: [grafana]

  splunk:
    image: splunk/splunk:latest
    container_name: splunk
    ports:
      - "8000:8000"   # UI web
      - "8088:8088"   # HEC
      - "8089:8089"   # Management API (opcional)
      - "9997:9997"   # Receiver p/ forwarders (opcional)
    environment:
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_PASSWORD: changeme123!
      SPLUNK_HEC_TOKEN: 00000000-0000-0000-0000-000000000000
      SPLUNK_GENERAL_TERMS: --accept-sgt-current-at-splunk-com
    volumes:
      - splunk-var:/opt/splunk/var
      - splunk-etc:/opt/splunk/etc
    restart: unless-stopped
    networks:
      logging:
        aliases: [splunk]

# ---------- Volumes persistentes ----------
volumes:
  redis-data:
  redisinsight-data:
  prometheus-data:
  grafana-storage:
  splunk-var:
  splunk-etc:
  redis-data-1:
  redis-data-2:
  redis-data-3:
  redis-data-4:
  redis-data-5:
  redis-data-6:

# ---------- Redes isoladas por domínio ----------
networks:
  backend:
    driver: bridge
  monitoring:
    driver: bridge
  logging:
    driver: bridge
  redis-cluster-net:
    driver: bridge
