services:
  redis:
    image: redis:latest
    container_name: redis
    command: ["redis-server", "--appendonly", "yes"] # habilita AOF (durabilidade)
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - redis-net

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    environment:
      - RI_ACCEPT_TERMS_AND_CONDITIONS=yes
    ports:
      - "5540:5540"   # UI do RedisInsight
    depends_on:
      - redis
    networks:
      - redis-net

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yaml

  grafana:
    image: grafana/grafana-oss:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  redis-data:
  grafana-storage:

networks:
  redis-net:
    driver: bridge
