global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'redis_exporter'
    static_configs:
      - targets: ['redis-exporter:9121']

  # sua app Kotlin (ex.: exposa /actuator/prometheus em :8080)
  - job_name: 'kotlin_app'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8080']  # se rodar a app local fora do container
