{
 "title": "Rate Limit Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "RPS - Total",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum (\r\n  rate(app_rate_limit_requests_total{allowed=\"true\"}[1m])\r\n)",
     "legendFormat": "tps"
    }
   ]
  },
  {
   "title": "Account - Total",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum by (account) (\r\n  rate(app_rate_limit_requests_total[1m])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Product- Total",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "sum by (product) (\r\n  rate(app_rate_limit_requests_total[1m])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Account",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum by (account, allowed) (\r\n  rate(app_rate_limit_requests_total[1m])\r\n)\r\n",
     "legendFormat": "{{account}} | allowed={{allowed}}"
    }
   ]
  },
  {
   "title": "Product",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "sum by (product, allowed) (\r\n  rate(app_rate_limit_requests_total[1m])\r\n)",
     "legendFormat": "{{product}} | allowed={{allowed}}"
    }
   ]
  },
  {
   "title": "Account- Allowed",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum by (account) (\r\n  rate(app_rate_limit_requests_total{allowed=\"true\"}[1m])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Product - Allowed",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "sum by (product) (\r\n  rate(app_rate_limit_requests_total{allowed=\"true\"}[1m])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Account- Disllowed",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "sum by (account) (\r\n  rate(app_rate_limit_requests_total{allowed=\"false\"}[1m])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Product - Disllowed",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "sum by (product) (\r\n  rate(app_rate_limit_requests_total{allowed=\"false\"}[1m])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}