global:
  scrape_interval: 15s
  evaluation_interval: 1s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # sua app Kotlin (ex.: /actuator/prometheus em :8080)
  - job_name: 'kotlin_app'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8080']  # app fora do container
