apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    uid: feyn6hnbpyqkgd        # mantenha igual ao JSON do dashboard
    url: http://prometheus:9090
    isDefault: true
    editable: true
